unit TestRedisClientU;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.Variants, IdTCPClient, Winapi.Windows, Vcl.Dialogs,
  Vcl.Forms, IdTCPConnection, Vcl.Controls, System.Classes, System.SysUtils,
  IdComponent, Winapi.Messages, IdBaseComponent, Vcl.Graphics, Vcl.StdCtrls,
  Redis.Client, Redis.Commons;

type
  // Test methods for class IRedisClient

  TestRedisClient = class(TTestCase)
  strict private
	 FRedis: IRedisClient;
  private
	 Res: string;
	 ArrRes: TArray<string>;
  public
	 procedure SetUp; override;
	 procedure TearDown; override;
  published
	 procedure TestCommandParser;
	 procedure TestExecuteWithStringArrayResponse;
	 procedure TestSetGet;
	 procedure TestSetGetUnicode;
	 procedure TestMSET;
	 procedure TestINCR;
	 procedure TestEXPIRE;
	 procedure TestDelete;
	 procedure TestRPUSH_RPOP;
	 procedure TestRPUSHX_LPUSHX;
	 procedure TestLPUSH_LPOP;
	 procedure TestLRANGE;
	 procedure TestLLEN;
	 procedure TestRPOPLPUSH;
	 procedure TestBLPOP;
	 procedure TestBRPOP;
	 procedure TestLREM;
	 procedure TestSELECT;
	 procedure TestMULTI;
	 procedure TestHSetHGet;
	 procedure TestHSetHGetUnicode;
	 // procedure TestSUBSCRIBE;
  end;

implementation

procedure TestRedisClient.SetUp;
begin
  FRedis := NewRedisClient('localhost', 6379, 'indy');
end;

procedure TestRedisClient.TearDown;
begin
  FRedis := nil;
end;

procedure TestRedisClient.TestBLPOP;
begin
  // setup list
  FRedis.DEL(['mylist']);
  FRedis.RPUSH('mylist', ['one', 'two']);

  // pop from a non-empty list
  CheckTrue(FRedis.BLPOP(['mylist'], 1, ArrRes));
  CheckEquals('mylist', ArrRes[0]);
  CheckEquals('one', ArrRes[1]);

  // pop from a non-empty list
  CheckTrue(FRedis.BLPOP(['mylist'], 1, ArrRes));
  CheckEquals('mylist', ArrRes[0]);
  CheckEquals('two', ArrRes[1]);

  // pop from a empty list, check the timeout
  CheckFalse(FRedis.BLPOP(['mylist'], 1, ArrRes));
  CheckEquals(0, Length(ArrRes));

  // now, test if it works when another thread pushes a values into the list
  TThread.CreateAnonymousThread(
    procedure
    var
      Redis: IRedisClient;
    begin
      Redis := NewRedisClient('localhost');
      Redis.RPUSH('mylist', ['from', 'another', 'thread']);
    end).Start;

  CheckTrue(FRedis.BLPOP(['mylist'], 10, ArrRes));
  CheckEquals(2, Length(ArrRes));
end;

procedure TestRedisClient.TestBRPOP;
begin
  // setup list
  FRedis.DEL(['mylist']);
  FRedis.RPUSH('mylist', ['one', 'two']);

  // pop from a non-empty list
  CheckTrue(FRedis.BRPOP(['mylist'], 1, ArrRes));
  CheckEquals('mylist', ArrRes[0]);
  CheckEquals('two', ArrRes[1]);

  // pop from a non-empty list
  CheckTrue(FRedis.BRPOP(['mylist'], 1, ArrRes));
  CheckEquals('mylist', ArrRes[0]);
  CheckEquals('one', ArrRes[1]);

  // pop from a empty list, check the timeout
  CheckFalse(FRedis.BRPOP(['mylist'], 1, ArrRes));
  CheckEquals(0, Length(ArrRes));

  // now, test if it works when another thread pushes a values into the list
  TThread.CreateAnonymousThread(
    procedure
    var
      Redis: IRedisClient;
    begin
      Redis := NewRedisClient('localhost');
      Redis.RPUSH('mylist', ['from', 'another', 'thread']);
    end).Start;

  CheckTrue(FRedis.BRPOP(['mylist'], 10, ArrRes));
  CheckEquals(2, Length(ArrRes));
end;

procedure TestRedisClient.TestCommandParser;
  procedure CheckSimpleSet;
  begin
    CheckEquals('set', ArrRes[0]);
    CheckEquals('nome', ArrRes[1]);
    CheckEquals('daniele', ArrRes[2]);
  end;

  procedure CheckSimpleSet2;
  begin
    CheckEquals('set', ArrRes[0]);
    CheckEquals('no me', ArrRes[1]);
    CheckEquals('da ni\ele', ArrRes[2]);
  end;

begin
  ArrRes := FRedis.Tokenize('set nome daniele');
  CheckSimpleSet;
  ArrRes := FRedis.Tokenize('set    nome  daniele');
  CheckSimpleSet;
  ArrRes := FRedis.Tokenize('   set    "nome"    daniele   ');
  CheckSimpleSet;
  ArrRes := FRedis.Tokenize('   set    "nome"    "daniele"   ');
  CheckSimpleSet;
  ArrRes := FRedis.Tokenize('set  nome "daniele"');
  CheckSimpleSet;
  ArrRes := FRedis.Tokenize('set  "no me" "da ni\ele"');
  CheckSimpleSet2;
  ExpectedException := ERedisException;
  ArrRes := FRedis.Tokenize('set nome "daniele');
end;

procedure TestRedisClient.TestDelete;
begin
  FRedis.&SET('NOME', 'Daniele');
  FRedis.&SET('COGNOME', 'Teti');
  CheckEquals(1, FRedis.DEL(['NOME']));
  CheckFalse(FRedis.GET('NOME', Res));
  CheckTrue(FRedis.GET('COGNOME', Res));
end;

procedure TestRedisClient.TestExecuteWithStringArrayResponse;
var
  Cmd: IRedisCommand;
begin
  FRedis.FLUSHDB;
  Cmd := NewRedisCommand('keys');
  Cmd.Add('*o*');
  CheckEquals(0, Length(FRedis.ExecuteAndGetArray(Cmd)));
  FRedis.&SET('1one', '1');
  FRedis.&SET('2one', '2');
  CheckEquals(2, Length(FRedis.ExecuteAndGetArray(Cmd)));
end;

procedure TestRedisClient.TestEXPIRE;
var
  v: string;
begin
  FRedis.&SET('daniele', '1234');
  FRedis.EXPIRE('daniele', 1);
  FRedis.GET('daniele', v);
  CheckEquals('1234', v);
  TThread.Sleep(2000);
  CheckFalse(FRedis.GET('daniele', v));
end;

procedure TestRedisClient.TestHSetHGet;
const
	C_KEY = '1000';
	C_field = 'leandro';
	C_VALUE = 'teste';
var
	aResult : string;
begin
	FRedis.DEL([C_KEY]);
	FRedis.HSET(C_KEY, C_field, C_VALUE);
	FRedis.HGET(C_KEY, C_field, aResult);
	CheckEqualsString(C_VALUE, aResult);
end;

procedure TestRedisClient.TestHSetHGetUnicode;
const
	C_KEY = '1000';
	C_field = 'leandro';
	C_VALUE = 'teste';
var
	aResult : Tbytes;
begin
	FRedis.DEL([C_KEY]);
	FRedis.HSET(C_KEY, C_field, TEncoding.Unicode.GetBytes(C_VALUE));
	FRedis.HGET(C_KEY, C_field, aResult);
	CheckEqualsString(C_VALUE, TEncoding.Unicode.GetString(aResult));
end;

procedure TestRedisClient.TestINCR;
begin
  FRedis.&SET('daniele', '-1');
  CheckEquals(0, FRedis.INCR('daniele'));
  FRedis.&SET('daniele', '1');
  CheckEquals(2, FRedis.INCR('daniele'));
end;

procedure TestRedisClient.TestLLEN;
begin
  FRedis.DEL(['mylist']);
  CheckEquals(0, FRedis.LLEN('mylist'));

  FRedis.RPUSH('mylist', ['one', 'two']);
  CheckEquals(2, FRedis.LLEN('mylist'));

  FRedis.&SET('myvalue', '3');
  ExpectedException := ERedisException;
  FRedis.LLEN('myvalue');
end;

procedure TestRedisClient.TestLPUSH_LPOP;
var
  Value: string;
begin
  FRedis.DEL(['mylist']);
  FRedis.LPUSH('mylist', ['one', 'two', 'three']);

  CheckTrue(FRedis.LPOP('mylist', Value));
  CheckEquals('three', Value);

  CheckTrue(FRedis.LPOP('mylist', Value));
  CheckEquals('two', Value);

  CheckTrue(FRedis.LPOP('mylist', Value));
  CheckEquals('one', Value);

  CheckFalse(FRedis.LPOP('mylist', Value))
end;

procedure TestRedisClient.TestLRANGE;
begin
  FRedis.DEL(['mylist']);
  FRedis.RPUSH('mylist', ['one', 'two', 'three', 'four', 'five']);
  ArrRes := FRedis.LRANGE('mylist', 0, 1);
  CheckEquals(2, Length(ArrRes));
  CheckEquals('one', ArrRes[0]);
  CheckEquals('two', ArrRes[1]);

  ArrRes := FRedis.LRANGE('mylist', -1, -1);
  CheckEquals(1, Length(ArrRes));
  CheckEquals('five', ArrRes[0]);

  ArrRes := FRedis.LRANGE('mylist', 0, 20);
  CheckEquals(5, Length(ArrRes));
  CheckEquals('one', ArrRes[0]);
  CheckEquals('two', ArrRes[1]);
  CheckEquals('three', ArrRes[2]);
  CheckEquals('four', ArrRes[3]);
  CheckEquals('five', ArrRes[4]);

  ArrRes := FRedis.LRANGE('notexists', 0, 20);
  CheckEquals(0, Length(ArrRes));
end;

procedure TestRedisClient.TestLREM;
begin
  FRedis.DEL(['mylist']);
  FRedis.RPUSH('mylist', ['hello', 'hello', 'foo', 'hello']);
  FRedis.LREM('mylist', -2, 'hello');
  ArrRes := FRedis.LRANGE('mylist', 0, -1);
  CheckEquals('hello', ArrRes[0]);
  CheckEquals('foo', ArrRes[1]);
end;

procedure TestRedisClient.TestMSET;
begin
  FRedis.FLUSHDB;
  CheckTrue(FRedis.MSET(['one', '1', 'two', '2', 'three', '3']));
  ArrRes := FRedis.KEYS('*e*');
  CheckEquals(2, Length(ArrRes));
end;

procedure TestRedisClient.TestMULTI;
var
  v: String;
begin
  ArrRes := FRedis.MULTI(
	 procedure(Redis: IRedisClient)
    begin
      Redis.&SET('name', 'Daniele');
      Redis.DEL(['name']);
    end);
  CheckEquals('OK', ArrRes[0]);
  CheckEquals('1', ArrRes[1]);
  CheckFalse(FRedis.GET('name', v));
end;

procedure TestRedisClient.TestRPOPLPUSH;
var
  Value: string;
begin
  FRedis.DEL(['mylist', 'myotherlist']);
  CheckFalse(FRedis.RPOPLPUSH('mylist', 'myotherlist', Value));
  CheckEquals('', Value);
  FRedis.RPUSH('mylist', ['one', 'two']);
  CheckEquals(true, FRedis.RPOPLPUSH('mylist', 'myotherlist', Value));
  CheckEquals('two', Value);
end;

procedure TestRedisClient.TestRPUSHX_LPUSHX;
begin
  FRedis.DEL(['mylist']);
  // mylist doesn't exists, so RPUSHX doesn't create it.
  CheckEquals(0, FRedis.RPUSHX('mylist', ['one']));
  CheckEquals(0, FRedis.LLEN('mylist'));

  // RPUSH creates mylist
  CheckEquals(1, FRedis.RPUSH('mylist', ['one']));
  CheckEquals(1, FRedis.LLEN('mylist'));

  // RPUSHX append to the list
  CheckEquals(2, FRedis.RPUSHX('mylist', ['two']));

  FRedis.DEL(['mylist']);
  CheckEquals(0, FRedis.LPUSHX('mylist', ['one']));
  CheckEquals(0, FRedis.LLEN('mylist'));
end;

procedure TestRedisClient.TestRPUSH_RPOP;
var
  Value: string;
begin
  FRedis.DEL(['mylist']);
  FRedis.RPUSH('mylist', ['one', 'two', 'three']);

  CheckTrue(FRedis.RPOP('mylist', Value));
  CheckEquals('three', Value);

  CheckTrue(FRedis.RPOP('mylist', Value));
  CheckEquals('two', Value);

  CheckTrue(FRedis.RPOP('mylist', Value));
  CheckEquals('one', Value);

  CheckEquals(False, FRedis.RPOP('mylist', Value));
end;

procedure TestRedisClient.TestSELECT;
var
  v: string;
begin
  FRedis.SELECT(0);
  FRedis.&SET('db0', 'value0');
  FRedis.SELECT(1);
  CheckFalse(FRedis.GET('db0', v));
  FRedis.SELECT(0);
  FRedis.GET('db0', v);
  CheckEquals('value0', v);
end;

procedure TestRedisClient.TestSetGet;
var
  Res: string;
begin
  CheckTrue(FRedis.&SET('nome', 'Daniele'));
  FRedis.GET('nome', Res);
  CheckEquals('Daniele', Res);

  CheckTrue(FRedis.&SET('no"me', 'Dan"iele'));
  CheckTrue(FRedis.GET('no"me', Res));
  CheckEquals('Dan"iele', Res);

  CheckTrue(FRedis.&SET('no"me', 'Dan iele'));
  CheckTrue(FRedis.GET('no"me', Res));
  CheckEquals('Dan iele', Res);
end;

procedure TestRedisClient.TestSetGetUnicode;
var
  Res: TBytes;
begin
  CheckTrue(FRedis.&SET(bytesof('nome'), TEncoding.Unicode.GetBytes('אטילעש')));
  CheckTrue(FRedis.GET(bytesof('nome'), Res));
  CheckEquals('אטילעש', TEncoding.Unicode.GetString(Res));
end;

// procedure TestRedisClient.TestSUBSCRIBE;
// var
// Rcv: NativeInt;
// MSG: string;
// X: NativeInt;
// begin
// //not implemented
// {
// AtomicExchange(Rcv, 0);
// // It's used for immediate real-time messaging, not for history storage
// FRedis.SUBSCRIBE(['ch1', 'ch2'],
// procedure(Channel, Message: string)
// begin
// MSG := message;
// AtomicIncrement(Rcv, 1);
// end);
// }
// {
// while true do
// begin
// X := AtomicCmpExchange(Rcv, -1, -1);
// TThread.Sleep(100)
// end;
// CheckEquals('hello', MSG);
// }
// end;

initialization

// Register any test cases with the test runner
RegisterTest(TestRedisClient.Suite);

end.
